name: Flujo de trabajo para construcción y pruebas por separado

on:
  workflow_dispatch:
  push:
    branches: [ V.0.2 ]
  pull_request:
    branches: [ V.0.2 ]
  schedule:
    - cron: '1 23 * * 0-4'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GHTOKEN }}
      GITHUB_OAUTH: ${{ secrets.GHTOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3

      - name: Configurando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Construcción del artefacto
        run: |
          chmod +x gradlew
          ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3

      - name: Configurando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Ejecutando pruebas
        run: |
          chmod +x gradlew
          ./gradlew test
